licencia

diff --git a/tor-strong b/tor-strong
--- a/tor-strong
+++ b/tor-strong
@@ -1,7 +1,9 @@
 #!/bin/bash
+# Made by Sinfallas <sinfallas@yahoo.com>
+# Licence: GPL-2
 if [[ $USER != root ]]; then
-echo -e "\e[00;31mERROR: must be root\e[00m"
-exit 1
+	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+	exit 1
 fi
 trap "rm -f /run/tor-strong.pid; exit" INT TERM EXIT
 echo $BASHPID > /run/tor-strong.pid
